"""add_email_reply_fields

Revision ID: 43637c752d26
Revises: ad32f906518c
Create Date: 2026-02-17 15:05:55.948842
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43637c752d26'
down_revision: Union[str, None] = 'ad32f906518c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('gmail_message_id', sa.String(length=255), nullable=True))
    op.add_column('emails', sa.Column('gmail_thread_id', sa.String(length=255), nullable=True))
    op.add_column('emails', sa.Column('is_outbound', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('emails', sa.Column('in_reply_to_id', sa.UUID(), nullable=True))
    op.add_column('emails', sa.Column('replied_by_id', sa.UUID(), nullable=True))
    op.create_index('ix_emails_gmail_thread', 'emails', ['gmail_thread_id'], unique=False)
    op.create_index(op.f('ix_emails_gmail_thread_id'), 'emails', ['gmail_thread_id'], unique=False)
    op.create_unique_constraint(None, 'emails', ['gmail_message_id'])
    op.create_foreign_key(None, 'emails', 'emails', ['in_reply_to_id'], ['id'])
    op.create_foreign_key(None, 'emails', 'users', ['replied_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_constraint(None, 'emails', type_='unique')
    op.drop_index(op.f('ix_emails_gmail_thread_id'), table_name='emails')
    op.drop_index('ix_emails_gmail_thread', table_name='emails')
    op.drop_column('emails', 'replied_by_id')
    op.drop_column('emails', 'in_reply_to_id')
    op.drop_column('emails', 'is_outbound')
    op.drop_column('emails', 'gmail_thread_id')
    op.drop_column('emails', 'gmail_message_id')
    # ### end Alembic commands ###
