"""add_gmail_credentials

Revision ID: ad32f906518c
Revises: 1b1eb6a15952
Create Date: 2026-02-17 14:17:09.954729
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad32f906518c'
down_revision: Union[str, None] = '1b1eb6a15952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gmail_address', sa.String(length=320), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_uri', sa.String(length=500), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_history_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gmail_credentials_active', 'gmail_credentials', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_gmail_credentials_user_id'), 'gmail_credentials', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gmail_credentials_user_id'), table_name='gmail_credentials')
    op.drop_index('ix_gmail_credentials_active', table_name='gmail_credentials')
    op.drop_table('gmail_credentials')
    # ### end Alembic commands ###
